
# Copyright 2021 .
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from setuptools import setup, find_packages
import datetime as dt


package_nm = 'runtime_client'
__version__ = "0.1.0"

base_requires = [
    "argparse >= 1.4.0",
    # "kfserving>=0.5.1",
    "dill >= 0.3.3",
    "joblib",
    "numpy",
    "pandas",
]

tests_require = [
    'pytest',
    'pytest-asyncio',
    'pytest-tornasync',
    'mypy'
]

client_requires = [
    "requests >= 2.25.1",
    "requests-toolbelt >= 0.9.1",
]


with open(f'{package_nm}/__version__.py', 'w') as f:
    version_py_module = f'''#-*- coding: utf-8 -*-
# This file is automatically generated by 'setup.py'
"""
Modified on {dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""
__all__ = ['__version__']

__version__ = '{__version__}'
'''
    f.write(version_py_module)


setup(
    name=package_nm,
    version=__version__,
    author_email='pydemia@gmail.com',
    license='https://github.com/kubeflow/kfserving/LICENSE',
    url='',
    description='Model Server implementation for AI Runtime.',
    long_description=open('README.md').read(),
    python_requires='>3.4',
    packages=find_packages(
        exclude=['contrib', 'docs', 'tests'],
    ),
    install_requires=base_requires + client_requires,
    tests_require=tests_require,
    extras_require={'test': tests_require}
)
